### ISSUE TITLE
Differences between lite and full runtime libraries?

### ISSUE THREAD

**Issue by Earlz** [squidfunk/protobluff#2]
I saw the documentation describing the differences, but I don't see how the generated lite and full runtime libraries are at all different. Searching "lite" on this repository doesn't really give any functional differences other than not generating accessors with protoc. Is there something I'm missing here?

**Comment by squidfunk** [comment]
## Lite runtime

The lite runtime only includes the encoding and decoding methods for working with the binary representation. It is as such kind of similar to *nanopb* which is a Protocol Buffers implementation for embedded environments.

### Encoding

When encoding a message you are responsible for holding state, so e.g. a nested submessage needs to be fully defined when encoding it, see:

https://github.com/squidfunk/protobluff/blob/f6ee42c15a4034b9d0fd0e597894b462516b1daa/examples/encoding/example.c#L50-L77

This means you cannot alter the message afterwards as everything is done in a single pass. If this is your actual use case, then you should use the lite runtime for encoding because it is faster than using the methods of the full runtime.

### Decoding

Decoding is similar to *nanopb* using callbacks for specific types, it's kind of similar to SAX parsing for XML, see:

https://github.com/squidfunk/protobluff/blob/f6ee42c15a4034b9d0fd0e597894b462516b1daa/examples/decoding/example.c#L68-L107

As every field is encountered you need to decide what to do with the field's value - you can ignore it or write it to the data structure you can provide via the third argument `void *user`. When decoding a message you can decide whether you want to decode a nested submessage or just skip it. Again, it's single pass.

### Limitations

The lite runtime cannot handle oneofs, as every value that is encountered is emitted. If you use the lite runtime with oneofs, decoding a message will report every encountered field possibly emitting multiple values for the same oneof (because Protocol Buffers messages can be concatenated) so you would be responsible for handling oneofs yourself.

## Full runtime

The full runtime includes the lite runtime and adds the possibility of writing, deleting or reading a very specific value inside an encoded Protocol Buffers message without the need for deserialization. It was the actual requirement why I built protobluff because I had to do a lot of updates on messages that needed to be synced to a datastore for which they needed to be serialized. Serialization was done every single time which was very expensive for large messages.

With protobluff you directly work on the underlying binary representation and can alter or read a single field inside the binary. The full runtime uses a journaling strategy for that, keeping an exact log of all updates that were carried out on the message. This is necessary because you can have several variables (fields, messages) pointing to the same underlying binary. If you update the binary in one part of your program, the other part would need to adjust its offsets before reading or writing, e.g.:

https://github.com/squidfunk/protobluff/blob/f6ee42c15a4034b9d0fd0e597894b462516b1daa/tests/message/message/test.c#L2393-L2421

The full runtime has full support for all Proto 2 features (except services, but that's a really open/opinionated specification). I hope this answers your question.

**Comment by Earlz** [comment]
I read the documentation, but I mean in the source code I see no differences between how the lite and full runtime libraries are built, and only one minor difference in how the protoc code is generated

**Comment by squidfunk** [comment]
The project is structured into four folders: `core`, `generator`, `message` and `util`. While the `generator` is built as an executable, the other sub-folders are built as intermediary libraries. Those intermediary libraries are then linked using `_LIBADD` into the lite and the full runtime. The lite runtime only includes the `core` intermediary library, the full runtime includes `core`, `message` and `util`. All of this is done using Autotools:

https://github.com/squidfunk/protobluff/blob/f6ee42c15a4034b9d0fd0e597894b462516b1daa/src/Makefile.am#L27-L51

**Comment by Earlz** [comment]
ah that was what I was looking for, thanks.
